'use client';
import {useEffect,useState} from 'react';
import {Truck,MapPin,Phone,ArrowUpLeft,PackageCheck,Menu} from 'lucide-react';
import {vehicles} from '@/lib/types';
import Register from './sw-register';
type Settings={phone:string;whatsapp:string;address:string;description:string};
export default function Home(){const [settings,setSettings]=useState<Settings>({phone:'',whatsapp:'',address:'',description:''});const [form,setForm]=useState({customer_name:'',customer_phone:'',pickup:'',destination:'',vehicle_type:'ٹرک',vehicle_count:1,goods_description:'',website:''});const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[menu,setMenu]=useState(false);
useEffect(()=>{fetch('/api/booking').then(r=>r.json()).then(d=>{if(!d.error)setSettings(d)}).catch(()=>{})},[]);
const set=(k:string,v:string|number)=>setForm(f=>({...f,[k]:v}));
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/booking',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw Error(data.error);setMessage(`درخواست محفوظ ہوگئی۔ آپ کا بکنگ نمبر ${data.booking_no} ہے۔`);setForm({customer_name:'',customer_phone:'',pickup:'',destination:'',vehicle_type:'ٹرک',vehicle_count:1,goods_description:'',website:''})}catch(e){setMessage(e instanceof Error?e.message:'خرابی پیش آگئی')}finally{setBusy(false)}}
return <><Register/><header className="site-header"><div className="container nav"><a className="brand" href="#top"><span className="brand-mark"><Truck size={28}/></span><span>الرحمن <small>کارگو سروس</small></span></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="مینو"><Menu/></button><nav className={menu?'open':''}><a href="#fleet" onClick={()=>setMenu(false)}>گاڑیاں</a><a href="#booking" onClick={()=>setMenu(false)}>بکنگ</a><a href="#contact" onClick={()=>setMenu(false)}>رابطہ</a><a className="nav-call" href={settings.phone?`tel:${settings.phone}`:'#contact'}>ابھی کال کریں <Phone size={17}/></a></nav></div></header>
<main id="top"><section className="hero"><div className="container hero-grid"><div><span className="eyebrow">آپ کے سامان کے سفر میں قابلِ اعتماد ساتھی</span><h1>جہاں سامان جانا ہو،<br/><em>الرحمن کارگو</em> ساتھ ہے۔</h1><p>ٹریلر، بیڈ فورڈ، ٹرک اور مزدا کی بکنگ۔ اپنی ضرورت بتائیں، ہم مناسب گاڑی کا انتظام کریں گے۔</p><div className="hero-actions"><a className="btn btn-gold" href="#booking">گاڑی بک کریں <ArrowUpLeft size={20}/></a>{settings.phone&&<a className="btn btn-outline" href={`tel:${settings.phone}`}>فون پر بات کریں <Phone size={18}/></a>}</div><div className="hero-proof"><span><PackageCheck size={19}/> سامان کی ترسیل</span><span><MapPin size={19}/> آپ کے روٹ کے مطابق</span></div></div><div className="hero-card"><div className="hero-card-top"><span>الرحمن کارگو سروس</span><Truck size={30}/></div><div className="route-line"><span>لوڈنگ پوائنٹ</span><div className="route-dots"><i/><b/><i/></div><span>منزل تک ترسیل</span></div><div className="fleet-mini">ٹریلر <span>•</span> بیڈ فورڈ <span>•</span> ٹرک <span>•</span> مزدا</div><a href="#booking">بکنگ کی درخواست دیں <ArrowUpLeft size={19}/></a></div></div></section>
<section className="fleet-section" id="fleet"><div className="container"><div className="section-head"><div><span className="overline">گاڑیوں کی سہولت</span><h2>ہر طرح کے لوڈ کے لیے گاڑی</h2></div><p>سامان کی نوعیت اور مقدار کے مطابق گاڑی منتخب کریں۔</p></div><div className="fleet-grid">{vehicles.map((v,i)=><a href="#booking" className="fleet-card" key={v} onClick={()=>set('vehicle_type',v)}><span className="fleet-num">۰{i+1}</span><Truck size={42} strokeWidth={1.4}/><h3>{v}</h3><span>بکنگ کریں <ArrowUpLeft size={18}/></span></a>)}</div></div></section>
<section className="booking-section" id="booking"><div className="container booking-grid"><div className="booking-copy"><span className="overline">بکنگ درخواست</span><h2>اپنی گاڑی<br/>آسانی سے بک کریں</h2><p>تفصیل بھیجیں۔ ہماری ٹیم آپ سے رابطہ کر کے کرایہ اور دستیابی کی تصدیق کرے گی۔</p><div className="step"><b>۱</b><span>لوڈنگ اور منزل درج کریں</span></div><div className="step"><b>۲</b><span>گاڑی اور تعداد منتخب کریں</span></div><div className="step"><b>۳</b><span>ہم آپ کو کال پر تصدیق دیں گے</span></div></div><form className="booking-form" onSubmit={submit}><h3>بکنگ کی تفصیل</h3><div className="form-grid"><label>آپ کا نام *<input required maxLength={120} value={form.customer_name} onChange={e=>set('customer_name',e.target.value)} placeholder="پورا نام"/></label><label>موبائل نمبر *<input required type="tel" value={form.customer_phone} onChange={e=>set('customer_phone',e.target.value)} placeholder="03XXXXXXXXX"/></label><label>لوڈنگ کہاں سے؟ *<input required value={form.pickup} onChange={e=>set('pickup',e.target.value)} placeholder="شہر / علاقہ"/></label><label>سامان کہاں پہنچانا ہے؟ *<input required value={form.destination} onChange={e=>set('destination',e.target.value)} placeholder="شہر / علاقہ"/></label><label>گاڑی کی قسم *<select value={form.vehicle_type} onChange={e=>set('vehicle_type',e.target.value)}>{vehicles.map(v=><option key={v}>{v}</option>)}</select></label><label>گاڑیوں کی تعداد *<input required type="number" min="1" max="100" value={form.vehicle_count} onChange={e=>set('vehicle_count',Number(e.target.value))}/></label><label className="full">سامان کی تفصیل<textarea rows={3} maxLength={300} value={form.goods_description} onChange={e=>set('goods_description',e.target.value)} placeholder="سامان کی نوعیت، وزن وغیرہ"/></label><input className="honeypot" tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>set('website',e.target.value)}/></div><button className="btn btn-gold submit" disabled={busy}>{busy?'درخواست بھیجی جا رہی ہے...':'بکنگ درخواست بھیجیں'}</button>{message&&<p role="status" className="form-message">{message}</p>}</form></div></section>
</main><footer id="contact"><div className="container footer-grid"><div><div className="brand"><span className="brand-mark"><Truck size={26}/></span><span>الرحمن <small>کارگو سروس</small></span></div><p>{settings.description||'آپ کے سامان کی ترسیل کے لیے ٹرانسپورٹ بکنگ کی سہولت۔'}</p></div><div><h4>رابطہ</h4>{settings.phone?<a href={`tel:${settings.phone}`}>{settings.phone}</a>:<span>رابطہ نمبر جلد شامل ہوگا</span>}{settings.whatsapp&&<a href={`https://wa.me/${settings.whatsapp}`} target="_blank" rel="noreferrer">واٹس ایپ پر رابطہ</a>}</div><div><h4>پتہ</h4><p>{settings.address||'ایڈمن پینل سے دفتر کا پتہ درج کریں۔'}</p><a href="/login" className="admin-link">ایڈمن لاگ اِن</a></div></div><div className="container footer-bottom">© {new Date().getFullYear()} الرحمن کارگو سروس</div></footer></>}
