import {Truck,MapPin,Phone,ArrowUpLeft,PackageCheck} from 'lucide-react';
import {vehicles} from '@/lib/types';
import {db} from '@/lib/db';
import BookingForm from './booking-form';

export const dynamic='force-dynamic';
type Settings={phone:string;phone2:string;phone3:string;email:string;whatsapp:string;address:string;description:string};
const defaults:Settings={phone:'+92 300 4842477',phone2:'+92 346 4842477',phone3:'+92 333 4842477',email:'alrehmancargo6692@gmail.com',whatsapp:'923004842477',address:'پلاٹ نمبر 31، نیو ٹرک اسٹینڈ، سبزہ زار، لاہور',description:'آپ کے سامان کی ترسیل کے لیے ٹرانسپورٹ بکنگ کی سہولت۔'};
async function getSettings():Promise<Settings>{try{const {data,error}=await db().from('cargo_settings').select('phone,phone2,phone3,email,whatsapp,address,description').eq('id',1).single();if(error||!data)return defaults;return {...defaults,...data}}catch{return defaults}}
export default async function Home(){const settings=await getSettings();return <>
<header className="site-header"><div className="container nav"><a className="brand" href="#top"><span className="brand-mark"><Truck size={28}/></span><span>الرحمن <small>کارگو سروسز</small></span></a><nav className="public-nav"><a href="#fleet">گاڑیاں</a><a href="#booking">بکنگ</a><a href="#contact">رابطہ</a><a className="nav-call" href={`tel:${settings.phone}`}>ابھی کال کریں <Phone size={17}/></a></nav></div></header>
<main id="top"><section className="hero"><div className="container hero-grid"><div><span className="eyebrow">آپ کے سامان کے سفر میں قابلِ اعتماد ساتھی</span><h1>جہاں سامان جانا ہو،<br/><em>الرحمن کارگو</em> ساتھ ہے۔</h1><p>ٹریلر، بیڈ فورڈ، ٹرک اور مزدا کی بکنگ۔ اپنی ضرورت بتائیں، ہم مناسب گاڑی کا انتظام کریں گے۔</p><div className="hero-actions"><a className="btn btn-gold" href="#booking">گاڑی بک کریں <ArrowUpLeft size={20}/></a><a className="btn btn-outline" href={`tel:${settings.phone}`}>فون پر بات کریں <Phone size={18}/></a></div><div className="hero-proof"><span><PackageCheck size={19}/> سامان کی ترسیل</span><span><MapPin size={19}/> آپ کے روٹ کے مطابق</span></div></div><div className="hero-card"><div className="hero-card-top"><span>الرحمن کارگو سروسز</span><Truck size={30}/></div><div className="route-line"><span>لوڈنگ پوائنٹ</span><div className="route-dots"><i/><b/><i/></div><span>منزل تک ترسیل</span></div><div className="fleet-mini">ٹریلر <span>•</span> بیڈ فورڈ <span>•</span> ٹرک <span>•</span> مزدا</div><a href="#booking">بکنگ کی درخواست دیں <ArrowUpLeft size={19}/></a></div></div></section>
<section className="fleet-section" id="fleet"><div className="container"><div className="section-head"><div><span className="overline">گاڑیوں کی سہولت</span><h2>ہر طرح کے لوڈ کے لیے گاڑی</h2></div><p>سامان کی نوعیت اور مقدار کے مطابق گاڑی منتخب کریں۔</p></div><div className="fleet-grid">{vehicles.map((vehicle,index)=><a href="#booking" className="fleet-card" key={vehicle}><span className="fleet-num">۰{index+1}</span><Truck size={42} strokeWidth={1.4}/><h3>{vehicle}</h3><span>بکنگ کریں <ArrowUpLeft size={18}/></span></a>)}</div></div></section>
<section className="booking-section" id="booking"><div className="container booking-grid"><div className="booking-copy"><span className="overline">بکنگ درخواست</span><h2>اپنی گاڑی<br/>آسانی سے بک کریں</h2><p>تفصیل بھیجیں۔ ہماری ٹیم آپ سے رابطہ کر کے کرایہ اور دستیابی کی تصدیق کرے گی۔</p><div className="step"><b>۱</b><span>لوڈنگ اور منزل درج کریں</span></div><div className="step"><b>۲</b><span>گاڑی اور تعداد منتخب کریں</span></div><div className="step"><b>۳</b><span>ہم آپ کو کال پر تصدیق دیں گے</span></div></div><BookingForm/></div></section></main>
<footer id="contact"><div className="container footer-grid"><div><div className="brand"><span className="brand-mark"><Truck size={26}/></span><span>الرحمن <small>کارگو سروسز</small></span></div><p>{settings.description}</p></div><div><h4>رابطہ</h4>{[settings.phone,settings.phone2,settings.phone3].filter(Boolean).map(phone=><a key={phone} dir="ltr" href={`tel:${phone}`}>{phone}</a>)}{settings.email&&<a href={`mailto:${settings.email}`}>{settings.email}</a>}{settings.whatsapp&&<a href={`https://wa.me/${settings.whatsapp}`} target="_blank" rel="noreferrer">واٹس ایپ پر رابطہ</a>}</div><div><h4>پتہ</h4><p>{settings.address}</p><a href="/login" className="admin-link">ایڈمن لاگ اِن</a></div></div><div className="container footer-bottom">© {new Date().getFullYear()} الرحمن کارگو سروسز</div></footer></>}
