'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {browserAuth} from '@/lib/client';
import {Booking,dateText,money,statuses,vehicles} from '@/lib/types';
import {Truck,Plus,Search,Printer,LogOut,Settings,LayoutDashboard,ClipboardList,X,Save,Trash2} from 'lucide-react';
type SettingsType={phone:string;whatsapp:string;address:string;description:string};
const empty={booking_date:new Date().toISOString().slice(0,10),customer_name:'',customer_phone:'',sender_name:'',receiver_name:'',receiver_phone:'',pickup:'',destination:'',vehicle_type:'ٹرک',vehicle_count:1,goods_description:'',weight:'',vehicle_number:'',driver_name:'',driver_phone:'',freight:0,owner_payment:0,other_expense:0,received:0,status:'تصدیق شدہ',notes:''};
export default function Admin(){const router=useRouter();const [rows,setRows]=useState<Booking[]>([]),[settings,setSettings]=useState<SettingsType>({phone:'',whatsapp:'',address:'',description:''}),[tab,setTab]=useState('dashboard'),[edit,setEdit]=useState<Partial<Booking>|null>(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('سب'),[error,setError]=useState(''),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false);
const authFetch=useCallback(async(url:string,options:RequestInit={})=>{const {data:{session}}=await browserAuth().auth.getSession();if(!session){router.replace('/login');throw Error('لاگ اِن کریں')}const r=await fetch(url,{...options,headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`,...options.headers}});if(r.status===401){router.replace('/login');throw Error('دوبارہ لاگ اِن کریں')}const data=await r.json();if(!r.ok)throw Error(data.error||'خرابی پیش آگئی');return data},[router]);
const load=useCallback(async()=>{try{setRows(await authFetch('/api/admin/bookings'));const r=await fetch('/api/booking');setSettings(await r.json())}catch(e){setError(e instanceof Error?e.message:'خرابی')}finally{setBusy(false)}},[authFetch]);useEffect(()=>{load()},[load]);
const filtered=useMemo(()=>rows.filter(r=>(filter==='سب'||r.status===filter)&&`${r.booking_no} ${r.customer_name} ${r.customer_phone} ${r.pickup} ${r.destination} ${r.vehicle_number||''}`.toLowerCase().includes(search.toLowerCase())),[rows,filter,search]);const active=rows.filter(r=>r.status!=='منسوخ');const sum=(key:keyof Booking)=>active.reduce((a,r)=>a+Number(r[key]||0),0);const due=active.reduce((a,r)=>a+Math.max(0,r.freight-r.received),0);const profit=sum('freight')-sum('owner_payment')-sum('other_expense');
async function save(){if(!edit)return;if(!edit.customer_name||!edit.customer_phone||!edit.pickup||!edit.destination){setError('نام، نمبر اور روٹ ضروری ہیں');return}setSaving(true);setError('');try{if(edit.id){await authFetch('/api/admin/bookings',{method:'PATCH',body:JSON.stringify(edit)})}else{const created=await fetch('/api/booking',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(edit)});const d=await created.json();if(!created.ok)throw Error(d.error);const newRows:Booking[]=await authFetch('/api/admin/bookings');const row=newRows.find(x=>x.booking_no===d.booking_no);if(row)await authFetch('/api/admin/bookings',{method:'PATCH',body:JSON.stringify({...edit,id:row.id})})}setEdit(null);await load()}catch(e){setError(e instanceof Error?e.message:'محفوظ نہیں ہوا')}finally{setSaving(false)}}
async function remove(r:Booking){if(!confirm(`بکنگ ${r.booking_no} مستقل حذف کریں؟`))return;try{await authFetch('/api/admin/bookings',{method:'DELETE',body:JSON.stringify({id:r.id})});await load()}catch(e){setError(e instanceof Error?e.message:'حذف نہیں ہوئی')}}
async function saveSettings(){setSaving(true);try{setSettings(await authFetch('/api/admin/settings',{method:'PATCH',body:JSON.stringify(settings)}));setError('سیٹنگز محفوظ ہوگئیں')}catch(e){setError(e instanceof Error?e.message:'خرابی')}finally{setSaving(false)}}
async function logout(){await browserAuth().auth.signOut();router.replace('/login')}
if(busy)return <main className="loading">ڈیٹا لوڈ ہو رہا ہے...</main>;
return <div className="admin-shell"><aside className="sidebar"><a href="/" className="brand sidebar-brand"><span className="brand-mark"><Truck size={24}/></span><span>الرحمن <small>کارگو سروس</small></span></a><div className="sidebar-caption">انتظامی پینل</div><button className={tab==='dashboard'?'selected':''} onClick={()=>setTab('dashboard')}><LayoutDashboard size={20}/> خلاصہ</button><button className={tab==='bookings'?'selected':''} onClick={()=>setTab('bookings')}><ClipboardList size={20}/> تمام بکنگز</button><button className={tab==='settings'?'selected':''} onClick={()=>setTab('settings')}><Settings size={20}/> ویب سائٹ سیٹنگز</button><div className="sidebar-end"><a href="/">ویب سائٹ دیکھیں</a><button onClick={logout}><LogOut size={19}/> لاگ آؤٹ</button></div></aside><main className="admin-main"><div className="admin-top"><div><span className="overline">کارگو منیجمنٹ</span><h1>{tab==='dashboard'?'کاروبار کا خلاصہ':tab==='bookings'?'بکنگ ریکارڈ':'ویب سائٹ سیٹنگز'}</h1></div><button className="btn btn-gold" onClick={()=>{setEdit(empty);setError('')}}><Plus size={20}/> نئی بکنگ</button></div>{error&&<div className="notice" role="status">{error}<button onClick={()=>setError('')}>×</button></div>}
{tab==='dashboard'&&<><div className="stat-grid"><Stat label="کل بکنگز" value={money(rows.length)}/><Stat label="کل کرایہ" value={`Rs ${money(sum('freight'))}`}/><Stat label="وصول شدہ" value={`Rs ${money(sum('received'))}`}/><Stat label="بقایا" value={`Rs ${money(due)}`}/><Stat label="گاڑی مالکان کی رقم" value={`Rs ${money(sum('owner_payment'))}`}/><Stat label="متوقع منافع" value={`Rs ${money(profit)}`}/></div><div className="panel"><div className="panel-heading"><h2>حالیہ بکنگز</h2><button className="text-button" onClick={()=>setTab('bookings')}>سب دیکھیں</button></div><BookingTable rows={rows.slice(0,6)} onEdit={setEdit} onRemove={remove}/></div></>}
{tab==='bookings'&&<div className="panel"><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="نام، نمبر، شہر یا بکنگ نمبر تلاش کریں" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>سب</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><BookingTable rows={filtered} onEdit={setEdit} onRemove={remove}/><div className="table-count">{filtered.length} ریکارڈ</div></div>}
{tab==='settings'&&<div className="panel settings-panel"><h2>رابطے کی معلومات</h2><p>یہ معلومات عوامی ویب سائٹ پر دکھائی دیں گی۔</p><div className="form-grid"><label>رابطہ نمبر<input value={settings.phone||''} onChange={e=>setSettings(s=>({...s,phone:e.target.value}))}/></label><label>واٹس ایپ نمبر (ملکی کوڈ کے ساتھ)<input dir="ltr" placeholder="923001234567" value={settings.whatsapp||''} onChange={e=>setSettings(s=>({...s,whatsapp:e.target.value}))}/></label><label className="full">دفتر کا پتہ<input value={settings.address||''} onChange={e=>setSettings(s=>({...s,address:e.target.value}))}/></label><label className="full">مختصر تعارف<textarea rows={3} value={settings.description||''} onChange={e=>setSettings(s=>({...s,description:e.target.value}))}/></label></div><button className="btn btn-gold" disabled={saving} onClick={saveSettings}><Save size={18}/> سیٹنگز محفوظ کریں</button></div>}
</main>{edit&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEdit(null)}}><div className="modal" role="dialog" aria-modal="true" aria-label="بکنگ کی تفصیل"><div className="modal-head"><div><span className="overline">{edit.id?edit.booking_no:'نیا ریکارڈ'}</span><h2>{edit.id?'بکنگ میں تبدیلی':'نئی بکنگ'}</h2></div><button aria-label="بند کریں" onClick={()=>setEdit(null)}><X/></button></div><div className="form-grid">{([['booking_date','بکنگ تاریخ','date'],['customer_name','کسٹمر کا نام','text'],['customer_phone','کسٹمر نمبر','tel'],['sender_name','بھیجنے والا','text'],['receiver_name','وصول کرنے والا','text'],['receiver_phone','وصول کنندہ نمبر','tel'],['pickup','لوڈنگ مقام','text'],['destination','منزل','text'],['vehicle_count','گاڑیوں کی تعداد','number'],['goods_description','سامان کی تفصیل','text'],['weight','وزن','text'],['vehicle_number','گاڑی نمبر','text'],['driver_name','ڈرائیور کا نام','text'],['driver_phone','ڈرائیور نمبر','tel'],['freight','کسٹمر سے طے کرایہ','number'],['owner_payment','گاڑی مالک کو ادائیگی','number'],['other_expense','دیگر خرچ','number'],['received','کسٹمر سے وصولی','number']] as const).map(([key,label,type])=><label key={key}>{label}<input type={type} min={type==='number'?0:undefined} value={String(edit[key]??'')} onChange={e=>setEdit(p=>({...p!,[key]:type==='number'?Number(e.target.value):e.target.value}))}/></label>)}<label>گاڑی کی قسم<select value={edit.vehicle_type||'ٹرک'} onChange={e=>setEdit(p=>({...p!,vehicle_type:e.target.value}))}>{vehicles.map(v=><option key={v}>{v}</option>)}</select></label><label>بکنگ کی حالت<select value={edit.status||'تصدیق شدہ'} onChange={e=>setEdit(p=>({...p!,status:e.target.value}))}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="full">نوٹس<textarea rows={2} value={edit.notes||''} onChange={e=>setEdit(p=>({...p!,notes:e.target.value}))}/></label></div><div className="modal-footer"><button className="btn btn-gold" disabled={saving} onClick={save}><Save size={18}/>{saving?'محفوظ ہو رہا ہے...':'محفوظ کریں'}</button>{edit.id&&<a className="btn btn-plain" target="_blank" href={`/print/${edit.id}`}><Printer size={18}/> بلٹی / انوائس</a>}</div>{error&&<p className="error">{error}</p>}</div></div>}</div>}
function Stat({label,value}:{label:string;value:string}){return <div className="stat"><span>{label}</span><strong dir="ltr">{value}</strong></div>}
function BookingTable({rows,onEdit,onRemove}:{rows:Booking[];onEdit:(r:Booking)=>void;onRemove:(r:Booking)=>void}){return <div className="table-wrap"><table><thead><tr><th>بکنگ نمبر</th><th>کسٹمر / رابطہ</th><th>روٹ</th><th>گاڑی</th><th>کرایہ</th><th>وصولی / بقایا</th><th>حالت</th><th>عمل</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b dir="ltr">{r.booking_no}</b><small>{dateText(r.booking_date||r.created_at)}</small></td><td>{r.customer_name}<small dir="ltr">{r.customer_phone}</small></td><td>{r.pickup} ← {r.destination}</td><td>{r.vehicle_type} × {r.vehicle_count}</td><td dir="ltr">{money(r.freight)}</td><td dir="ltr">{money(r.received)} / {money(Math.max(0,r.freight-r.received))}</td><td><span className="status">{r.status}</span></td><td><div className="row-actions"><button title="تبدیل کریں" onClick={()=>onEdit(r)}><Settings size={16}/></button><a title="بلٹی / انوائس" href={`/print/${r.id}`} target="_blank"><Printer size={16}/></a><button title="حذف کریں" onClick={()=>onRemove(r)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">کوئی بکنگ نہیں ملی۔</div>}</div>}
